//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.4.1
//     from Assets/New Controls.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

namespace NewControlsNamespace
{
    public partial class @NewControls : IInputActionCollection2, IDisposable
    {
        public InputActionAsset asset { get; }
        public @NewControls()
        {
            asset = InputActionAsset.FromJson(@"{
    ""name"": ""New Controls"",
    ""maps"": [
        {
            ""name"": ""Buttons"",
            ""id"": ""827e5c73-53d0-4894-981d-8136f9b2c822"",
            ""actions"": [
                {
                    ""name"": ""ButtonClick"",
                    ""type"": ""Button"",
                    ""id"": ""e6597ea3-a0b1-44ff-b198-b91ea02da80e"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""640b941d-d20a-477b-9ec6-e518417d15f6"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ButtonClick"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""4fa8a779-0860-4ce3-907e-b0f671b203a2"",
                    ""path"": ""<VirtualMouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ButtonClick"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""44109118-69a6-43dd-94ed-999ca27213c0"",
                    ""path"": ""<Gamepad>/leftShoulder"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ButtonClick"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""Movement"",
            ""id"": ""1325b081-79a4-4f1b-ac27-2e107a6de4a8"",
            ""actions"": [
                {
                    ""name"": ""VerticalAxis"",
                    ""type"": ""Button"",
                    ""id"": ""91c43831-9911-4be9-9c53-d929147c888b"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""HorizontalAxis"",
                    ""type"": ""Button"",
                    ""id"": ""402de01d-0234-47ee-94d5-1886c64632e9"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": ""Move"",
                    ""id"": ""4afaf337-28e4-48d8-9d8d-57ba7011ecfb"",
                    ""path"": ""1DAxis"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""VerticalAxis"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""negative"",
                    ""id"": ""e29f2201-4834-40d3-adbe-46c62afe6e95"",
                    ""path"": ""<Joystick>/stick/down"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""VerticalAxis"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""positive"",
                    ""id"": ""f09a6975-de18-44a0-b1dc-ffc782562515"",
                    ""path"": ""<Joystick>/stick/up"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""VerticalAxis"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""GamepadRightStick"",
                    ""id"": ""154cb6c7-ecd1-4ec0-aae5-fb6c976a833c"",
                    ""path"": ""1DAxis"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""VerticalAxis"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""negative"",
                    ""id"": ""85a6cc16-13cd-4977-bd68-729016378434"",
                    ""path"": ""<Gamepad>/rightStick/down"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""VerticalAxis"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""positive"",
                    ""id"": ""74ef5e60-773c-4b18-9cb2-7fb8285c32d9"",
                    ""path"": ""<Gamepad>/rightStick/up"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""VerticalAxis"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""GamepadLeftStick"",
                    ""id"": ""14e3fce3-da36-4d21-8c1a-939ce2e8dc54"",
                    ""path"": ""1DAxis"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""VerticalAxis"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""negative"",
                    ""id"": ""1c27c3d7-0de3-4913-ae7e-2cdf702e6c8a"",
                    ""path"": ""<Gamepad>/leftStick/down"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""VerticalAxis"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""positive"",
                    ""id"": ""326b9fda-03ac-485f-86e5-104fd3027207"",
                    ""path"": ""<Gamepad>/leftStick/up"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""VerticalAxis"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""GamepadDPad"",
                    ""id"": ""8438263b-4f6a-4f42-aa82-8302ea432f86"",
                    ""path"": ""1DAxis"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""VerticalAxis"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""negative"",
                    ""id"": ""6ed2d823-d977-4796-ad67-010a237a5b42"",
                    ""path"": ""<Gamepad>/dpad/down"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""VerticalAxis"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""positive"",
                    ""id"": ""25a57910-391f-475e-ae83-7e25cbca66f8"",
                    ""path"": ""<Gamepad>/dpad/up"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""VerticalAxis"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""Move"",
                    ""id"": ""827c7f8a-2b03-4e2c-995b-ebec0059cbc5"",
                    ""path"": ""1DAxis"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""HorizontalAxis"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""negative"",
                    ""id"": ""84d6aad2-3128-44ea-ae6b-8f314b4c73d0"",
                    ""path"": ""<Joystick>/stick/left"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""HorizontalAxis"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""positive"",
                    ""id"": ""24585a64-8f2f-4774-8a9b-8656f94a255c"",
                    ""path"": ""<Joystick>/stick/right"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""HorizontalAxis"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""GamepadRightStick"",
                    ""id"": ""de6cdf3d-f246-4b2a-9832-0e748d603170"",
                    ""path"": ""1DAxis"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""HorizontalAxis"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""negative"",
                    ""id"": ""4ac1a712-bf4a-449e-a2a3-282ca2121fc7"",
                    ""path"": ""<Gamepad>/rightStick/left"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""HorizontalAxis"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""positive"",
                    ""id"": ""db3b94b1-95f8-4dce-a055-b2a9ff263562"",
                    ""path"": ""<Gamepad>/rightStick/right"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""HorizontalAxis"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""GamepadLeftStick"",
                    ""id"": ""191ec069-100d-43ba-8aea-fcc5793db895"",
                    ""path"": ""1DAxis"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""HorizontalAxis"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""negative"",
                    ""id"": ""089c2e41-8130-4e33-ba00-1725a894cb75"",
                    ""path"": ""<Gamepad>/leftStick/left"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""HorizontalAxis"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""positive"",
                    ""id"": ""2af929a7-bdc5-4f31-83f8-187f18e38065"",
                    ""path"": ""<Gamepad>/leftStick/right"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""HorizontalAxis"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""GamepadDPad"",
                    ""id"": ""2f8f28ff-ca87-425c-b70d-1fde3b77ee0f"",
                    ""path"": ""1DAxis"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""HorizontalAxis"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""negative"",
                    ""id"": ""0740c3b2-7f96-4d03-aec1-28d917d6cc70"",
                    ""path"": ""<Gamepad>/dpad/left"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""HorizontalAxis"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""positive"",
                    ""id"": ""2bdd155f-653b-44e4-8a4f-9af13252a555"",
                    ""path"": ""<Gamepad>/dpad/right"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""HorizontalAxis"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                }
            ]
        },
        {
            ""name"": ""Scrolling"",
            ""id"": ""4bc555c1-883a-4a87-b362-5eba1d412106"",
            ""actions"": [
                {
                    ""name"": ""Scroll"",
                    ""type"": ""Button"",
                    ""id"": ""7541ed53-5f5c-4a31-af68-8dff65f6e0f9"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""HorScroll"",
                    ""type"": ""Button"",
                    ""id"": ""2d568a26-1faa-4f1d-baae-2893d3ee2dc4"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": ""ButtonScroll"",
                    ""id"": ""fdf14c1a-ad1f-424e-802b-1fc07209e0d4"",
                    ""path"": ""1DAxis"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Scroll"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""negative"",
                    ""id"": ""adaad0b0-63a3-4e6a-aa97-259206577b93"",
                    ""path"": ""<Joystick>/trigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Scroll"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""positive"",
                    ""id"": ""9fa08e1d-39be-43ae-8134-0c35ac48cb1b"",
                    ""path"": ""<HID::ࠁ 205C33634243>/button5"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Scroll"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""GamePadScroll"",
                    ""id"": ""bef956b9-9747-4ce9-a515-bb96e0ba5d7e"",
                    ""path"": ""1DAxis"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Scroll"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""positive"",
                    ""id"": ""311fb282-94ca-4bfb-9210-4672f36102cb"",
                    ""path"": ""<Gamepad>/buttonSouth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Scroll"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""negative"",
                    ""id"": ""7c10a2bf-8f28-4142-95bd-ce1df7f8a534"",
                    ""path"": ""<Gamepad>/buttonNorth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Scroll"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""1D Axis"",
                    ""id"": ""e74759e2-902f-435b-b007-f1cebf3a6469"",
                    ""path"": ""1DAxis"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""HorScroll"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""negative"",
                    ""id"": ""c69ee0e3-44c6-4a6e-ab14-6912d099f6e2"",
                    ""path"": ""<Gamepad>/buttonWest"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""HorScroll"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""positive"",
                    ""id"": ""2ff5322c-bb1a-4555-aaf6-c3476501a9a5"",
                    ""path"": ""<Gamepad>/buttonEast"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""HorScroll"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
            // Buttons
            m_Buttons = asset.FindActionMap("Buttons", throwIfNotFound: true);
            m_Buttons_ButtonClick = m_Buttons.FindAction("ButtonClick", throwIfNotFound: true);
            // Movement
            m_Movement = asset.FindActionMap("Movement", throwIfNotFound: true);
            m_Movement_VerticalAxis = m_Movement.FindAction("VerticalAxis", throwIfNotFound: true);
            m_Movement_HorizontalAxis = m_Movement.FindAction("HorizontalAxis", throwIfNotFound: true);
            // Scrolling
            m_Scrolling = asset.FindActionMap("Scrolling", throwIfNotFound: true);
            m_Scrolling_Scroll = m_Scrolling.FindAction("Scroll", throwIfNotFound: true);
            m_Scrolling_HorScroll = m_Scrolling.FindAction("HorScroll", throwIfNotFound: true);
        }

        public void Dispose()
        {
            UnityEngine.Object.Destroy(asset);
        }

        public InputBinding? bindingMask
        {
            get => asset.bindingMask;
            set => asset.bindingMask = value;
        }

        public ReadOnlyArray<InputDevice>? devices
        {
            get => asset.devices;
            set => asset.devices = value;
        }

        public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

        public bool Contains(InputAction action)
        {
            return asset.Contains(action);
        }

        public IEnumerator<InputAction> GetEnumerator()
        {
            return asset.GetEnumerator();
        }

        IEnumerator IEnumerable.GetEnumerator()
        {
            return GetEnumerator();
        }

        public void Enable()
        {
            asset.Enable();
        }

        public void Disable()
        {
            asset.Disable();
        }
        public IEnumerable<InputBinding> bindings => asset.bindings;

        public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
        {
            return asset.FindAction(actionNameOrId, throwIfNotFound);
        }
        public int FindBinding(InputBinding bindingMask, out InputAction action)
        {
            return asset.FindBinding(bindingMask, out action);
        }

        // Buttons
        private readonly InputActionMap m_Buttons;
        private IButtonsActions m_ButtonsActionsCallbackInterface;
        private readonly InputAction m_Buttons_ButtonClick;
        public struct ButtonsActions
        {
            private @NewControls m_Wrapper;
            public ButtonsActions(@NewControls wrapper) { m_Wrapper = wrapper; }
            public InputAction @ButtonClick => m_Wrapper.m_Buttons_ButtonClick;
            public InputActionMap Get() { return m_Wrapper.m_Buttons; }
            public void Enable() { Get().Enable(); }
            public void Disable() { Get().Disable(); }
            public bool enabled => Get().enabled;
            public static implicit operator InputActionMap(ButtonsActions set) { return set.Get(); }
            public void SetCallbacks(IButtonsActions instance)
            {
                if (m_Wrapper.m_ButtonsActionsCallbackInterface != null)
                {
                    @ButtonClick.started -= m_Wrapper.m_ButtonsActionsCallbackInterface.OnButtonClick;
                    @ButtonClick.performed -= m_Wrapper.m_ButtonsActionsCallbackInterface.OnButtonClick;
                    @ButtonClick.canceled -= m_Wrapper.m_ButtonsActionsCallbackInterface.OnButtonClick;
                }
                m_Wrapper.m_ButtonsActionsCallbackInterface = instance;
                if (instance != null)
                {
                    @ButtonClick.started += instance.OnButtonClick;
                    @ButtonClick.performed += instance.OnButtonClick;
                    @ButtonClick.canceled += instance.OnButtonClick;
                }
            }
        }
        public ButtonsActions @Buttons => new ButtonsActions(this);

        // Movement
        private readonly InputActionMap m_Movement;
        private IMovementActions m_MovementActionsCallbackInterface;
        private readonly InputAction m_Movement_VerticalAxis;
        private readonly InputAction m_Movement_HorizontalAxis;
        public struct MovementActions
        {
            private @NewControls m_Wrapper;
            public MovementActions(@NewControls wrapper) { m_Wrapper = wrapper; }
            public InputAction @VerticalAxis => m_Wrapper.m_Movement_VerticalAxis;
            public InputAction @HorizontalAxis => m_Wrapper.m_Movement_HorizontalAxis;
            public InputActionMap Get() { return m_Wrapper.m_Movement; }
            public void Enable() { Get().Enable(); }
            public void Disable() { Get().Disable(); }
            public bool enabled => Get().enabled;
            public static implicit operator InputActionMap(MovementActions set) { return set.Get(); }
            public void SetCallbacks(IMovementActions instance)
            {
                if (m_Wrapper.m_MovementActionsCallbackInterface != null)
                {
                    @VerticalAxis.started -= m_Wrapper.m_MovementActionsCallbackInterface.OnVerticalAxis;
                    @VerticalAxis.performed -= m_Wrapper.m_MovementActionsCallbackInterface.OnVerticalAxis;
                    @VerticalAxis.canceled -= m_Wrapper.m_MovementActionsCallbackInterface.OnVerticalAxis;
                    @HorizontalAxis.started -= m_Wrapper.m_MovementActionsCallbackInterface.OnHorizontalAxis;
                    @HorizontalAxis.performed -= m_Wrapper.m_MovementActionsCallbackInterface.OnHorizontalAxis;
                    @HorizontalAxis.canceled -= m_Wrapper.m_MovementActionsCallbackInterface.OnHorizontalAxis;
                }
                m_Wrapper.m_MovementActionsCallbackInterface = instance;
                if (instance != null)
                {
                    @VerticalAxis.started += instance.OnVerticalAxis;
                    @VerticalAxis.performed += instance.OnVerticalAxis;
                    @VerticalAxis.canceled += instance.OnVerticalAxis;
                    @HorizontalAxis.started += instance.OnHorizontalAxis;
                    @HorizontalAxis.performed += instance.OnHorizontalAxis;
                    @HorizontalAxis.canceled += instance.OnHorizontalAxis;
                }
            }
        }
        public MovementActions @Movement => new MovementActions(this);

        // Scrolling
        private readonly InputActionMap m_Scrolling;
        private IScrollingActions m_ScrollingActionsCallbackInterface;
        private readonly InputAction m_Scrolling_Scroll;
        private readonly InputAction m_Scrolling_HorScroll;
        public struct ScrollingActions
        {
            private @NewControls m_Wrapper;
            public ScrollingActions(@NewControls wrapper) { m_Wrapper = wrapper; }
            public InputAction @Scroll => m_Wrapper.m_Scrolling_Scroll;
            public InputAction @HorScroll => m_Wrapper.m_Scrolling_HorScroll;
            public InputActionMap Get() { return m_Wrapper.m_Scrolling; }
            public void Enable() { Get().Enable(); }
            public void Disable() { Get().Disable(); }
            public bool enabled => Get().enabled;
            public static implicit operator InputActionMap(ScrollingActions set) { return set.Get(); }
            public void SetCallbacks(IScrollingActions instance)
            {
                if (m_Wrapper.m_ScrollingActionsCallbackInterface != null)
                {
                    @Scroll.started -= m_Wrapper.m_ScrollingActionsCallbackInterface.OnScroll;
                    @Scroll.performed -= m_Wrapper.m_ScrollingActionsCallbackInterface.OnScroll;
                    @Scroll.canceled -= m_Wrapper.m_ScrollingActionsCallbackInterface.OnScroll;
                    @HorScroll.started -= m_Wrapper.m_ScrollingActionsCallbackInterface.OnHorScroll;
                    @HorScroll.performed -= m_Wrapper.m_ScrollingActionsCallbackInterface.OnHorScroll;
                    @HorScroll.canceled -= m_Wrapper.m_ScrollingActionsCallbackInterface.OnHorScroll;
                }
                m_Wrapper.m_ScrollingActionsCallbackInterface = instance;
                if (instance != null)
                {
                    @Scroll.started += instance.OnScroll;
                    @Scroll.performed += instance.OnScroll;
                    @Scroll.canceled += instance.OnScroll;
                    @HorScroll.started += instance.OnHorScroll;
                    @HorScroll.performed += instance.OnHorScroll;
                    @HorScroll.canceled += instance.OnHorScroll;
                }
            }
        }
        public ScrollingActions @Scrolling => new ScrollingActions(this);
        public interface IButtonsActions
        {
            void OnButtonClick(InputAction.CallbackContext context);
        }
        public interface IMovementActions
        {
            void OnVerticalAxis(InputAction.CallbackContext context);
            void OnHorizontalAxis(InputAction.CallbackContext context);
        }
        public interface IScrollingActions
        {
            void OnScroll(InputAction.CallbackContext context);
            void OnHorScroll(InputAction.CallbackContext context);
        }
    }
}
